config/routes.rb
FootballStats::Application.routes.draw do
  get "welcome/home"
  get "welcome/help"
  resources :player_stats

  resources :players

  resources :teams

  resources :events

  resources :combines

end

app/models/combine.rb
class Combine < ActiveRecord::Base
end

app/controllers/combines_controller.rb
class CombinesController < ApplicationController
  before_action :set_combine, only: [:show, :edit, :update, :destroy]

  # GET /combines
  # GET /combines.json
  def index
    @combines = Combine.all
  end

  # GET /combines/1
  # GET /combines/1.json
  def show
  end

  # GET /combines/new
  def new
    @combine = Combine.new
  end

  # GET /combines/1/edit
  def edit
  end

  # POST /combines
  # POST /combines.json
  def create
    @combine = Combine.new(combine_params)

    respond_to do |format|
      if @combine.save
        format.html { redirect_to @combine, notice: 'Combine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @combine }
      else
        format.html { render action: 'new' }
        format.json { render json: @combine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combines/1
  # PATCH/PUT /combines/1.json
  def update
    respond_to do |format|
      if @combine.update(combine_params)
        format.html { redirect_to @combine, notice: 'Combine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @combine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combines/1
  # DELETE /combines/1.json
  def destroy
    @combine.destroy
    respond_to do |format|
      format.html { redirect_to combines_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combine
      @combine = Combine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combine_params
      params.require(:combine).permit(:name, :college, :position, :_40_yd_dash, :bench_press, :vertical_jump)
    end
end

app/helpers/combines_helper.rb
module CombinesHelper
end

app/views/combines/_form.html.erb
<%= form_for(@combine) do |f| %>
  <% if @combine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@combine.errors.count, "error") %> prohibited this combine from being saved:</h2>

      <ul>
      <% @combine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :college %><br>
    <%= f.text_field :college %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :_40_yd_dash %><br>
    <%= f.text_field :_40_yd_dash %>
  </div>
  <div class="field">
    <%= f.label :bench_press %><br>
    <%= f.number_field :bench_press %>
  </div>
  <div class="field">
    <%= f.label :vertical_jump %><br>
    <%= f.text_field :vertical_jump %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/combines/edit.html.erb
<h1>Editing combine</h1>

<%= render 'form' %>

<%= link_to 'Show', @combine %> |
<%= link_to 'Back', combines_path %>

app/views/combines/index.html.erb
<h1>Players</h1>

<table id ="players">
  <thead>
    <tr>
      <th>Name</th>
      <th>College</th>
      <th>Position</th>
      <th> 40 yd dash</th>
      <th>Bench press</th>
      <th>Vertical jump</th>    
    </tr>
  </thead>

  <tbody>
    <% @combines.each do |combine| %>
      <tr>
        <td><%= combine.name %></td>
        <td><%= combine.college %></td>
        <td><%= combine.position %></td>
        <td><%= combine._40_yd_dash %></td>
        <td><%= combine.bench_press %></td>
        <td><%= combine.vertical_jump %></td>      
      </tr>
    <% end %>
  </tbody>
</table>

app/views/combines/new.html.erb
<h1>New combine</h1>

<%= render 'form' %>

<%= link_to 'Back', combines_path %>

app/views/combines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @combine.name %>
</p>

<p>
  <strong>College:</strong>
  <%= @combine.college %>
</p>

<p>
  <strong>Position:</strong>
  <%= @combine.position %>
</p>

<p>
  <strong> 40 yd dash:</strong>
  <%= @combine._40_yd_dash %>
</p>

<p>
  <strong>Bench press:</strong>
  <%= @combine.bench_press %>
</p>

<p>
  <strong>Vertical jump:</strong>
  <%= @combine.vertical_jump %>
</p>

<%= link_to 'Edit', edit_combine_path(@combine) %> |
<%= link_to 'Back', combines_path %>