config/routes.rb
FootballStats::Application.routes.draw do
  get "welcome/home"
  get "welcome/help"
  resources :player_stats

  resources :players

  resources :teams

  resources :events

  resources :combines

end

app/models/player_stat.rb
class PlayerStat < ActiveRecord::Base
end

app/controllers/player_stats_controller.rb
class PlayerStatsController < ApplicationController
  before_action :set_player_stat, only: [:show, :edit, :update, :destroy]

  # GET /player_stats
  # GET /player_stats.json
  def index
    @player_stats = PlayerStat.all
  end

  # GET /player_stats/1
  # GET /player_stats/1.json
  def show
  end

  # GET /player_stats/new
  def new
    @player_stat = PlayerStat.new
  end

  # GET /player_stats/1/edit
  def edit
  end

  # POST /player_stats
  # POST /player_stats.json
  def create
    @player_stat = PlayerStat.new(player_stat_params)

    respond_to do |format|
      if @player_stat.save
        format.html { redirect_to @player_stat, notice: 'Player stat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player_stat }
      else
        format.html { render action: 'new' }
        format.json { render json: @player_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_stats/1
  # PATCH/PUT /player_stats/1.json
  def update
    respond_to do |format|
      if @player_stat.update(player_stat_params)
        format.html { redirect_to @player_stat, notice: 'Player stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_stats/1
  # DELETE /player_stats/1.json
  def destroy
    @player_stat.destroy
    respond_to do |format|
      format.html { redirect_to player_stats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_stat
      @player_stat = PlayerStat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_stat_params
      params.require(:player_stat).permit(:player_id, :stats)
    end
end

app/helpers/player_stats_helper.rb
module PlayerStatsHelper
end

app/views/player_stats/_form.html.erb
<%= form_for(@player_stat) do |f| %>
  <% if @player_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_stat.errors.count, "error") %> prohibited this player_stat from being saved:</h2>

      <ul>
      <% @player_stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :stats %><br>
    <%= f.text_field :stats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_stats/edit.html.erb
<h1>Editing player_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_stat %> |
<%= link_to 'Back', player_stats_path %>

app/views/player_stats/index.html.erb
<h1>Listing player_stats</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Stats</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @player_stats.each do |player_stat| %>
      <tr>
        <td><%= player_stat.player_id %></td>
        <td><%= player_stat.stats %></td>
        <td><%= link_to 'Show', player_stat %></td>
        <td><%= link_to 'Edit', edit_player_stat_path(player_stat) %></td>
        <td><%= link_to 'Destroy', player_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player stat', new_player_stat_path %>

app/views/player_stats/new.html.erb
<h1>New player_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', player_stats_path %>

app/views/player_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @player_stat.player_id %>
</p>

<p>
  <strong>Stats:</strong>
  <%= @player_stat.stats %>
</p>

<%= link_to 'Edit', edit_player_stat_path(@player_stat) %> |
<%= link_to 'Back', player_stats_path %>